# Generated by Django 5.2.6 on 2025-09-16 17:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('service_type', models.CharField(choices=[('equipment', 'معدات'), ('staff', 'طاقم عمل'), ('decoration', 'ديكور'), ('entertainment', 'ترفيه'), ('photography', 'تصوير'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الخدمة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('price_unit', models.CharField(choices=[('hour', 'ساعة'), ('day', 'يوم'), ('event', 'للفعالية'), ('person', 'للفرد'), ('unit', 'قطعة')], max_length=10, verbose_name='وحدة السعر')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يتطلب موافقة')),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للكمية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='صورة الخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خدمة إضافية',
                'verbose_name_plural': 'الخدمات الإضافية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خدمة الحجز',
                'verbose_name_plural': 'خدمات الحجز',
            },
        ),
        migrations.CreateModel(
            name='BookingServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الخدمة')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('special_requirements', models.TextField(blank=True, null=True, verbose_name='متطلبات خاصة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خدمة مطلوبة في الحجز',
                'verbose_name_plural': 'الخدمات المطلوبة في الحجوزات',
                'ordering': ['start_time', 'service__name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-building', max_length=50, verbose_name='الأيقونة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المدينة/المركز')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('is_capital', models.BooleanField(default=False, verbose_name='عاصمة المحافظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مدينة/مركز',
                'verbose_name_plural': 'المدن والمراكز',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
            ],
            options={
                'verbose_name': 'رسالة اتصال',
                'verbose_name_plural': 'رسائل الاتصال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المحافظة')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود المحافظة')),
                ('region', models.CharField(choices=[('cairo', 'القاهرة الكبرى'), ('delta', 'الدلتا'), ('canal', 'قناة السويس'), ('sinai', 'سيناء'), ('north_upper', 'صعيد مصر العليا'), ('south_upper', 'صعيد مصر السفلى'), ('north_coast', 'الساحل الشمالي'), ('red_sea', 'البحر الأحمر'), ('new_valley', 'الوادي الجديد')], max_length=50, verbose_name='المنطقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القاعة')),
                ('address', models.TextField(help_text='الشارع، الحي، معالم مميزة', verbose_name='العنوان التفصيلي')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('capacity', models.PositiveIntegerField(verbose_name='السعة')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر للساعة')),
                ('image', models.ImageField(upload_to='halls/', verbose_name='الصورة')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('maintenance', 'صيانة'), ('booked', 'محجوز')], default='available', max_length=20, verbose_name='الحالة')),
                ('features', models.JSONField(default=list, verbose_name='المميزات')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قاعة',
                'verbose_name_plural': 'القاعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='halls/gallery/', verbose_name='الصورة')),
                ('image_type', models.CharField(choices=[('main', 'صورة رئيسية'), ('gallery', 'معرض الصور'), ('interior', 'صور داخلية'), ('exterior', 'صور خارجية'), ('facilities', 'صور المرافق')], default='gallery', max_length=20, verbose_name='نوع الصورة')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الصورة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الصورة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='صورة مميزة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'صورة القاعة',
                'verbose_name_plural': 'صور القاعات',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HallManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'عرض فقط'), ('manage', 'إدارة كاملة'), ('schedule', 'إدارة الجدولة فقط')], default='manage', max_length=20, verbose_name='مستوى الصلاحية')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مدير القاعة',
                'verbose_name_plural': 'مديرو القاعات',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='HallMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('extra_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='اتركه فارغاً لاستخدام السعر الافتراضي للوجبة', max_digits=10, null=True, verbose_name='تعديل السعر (اختياري)')),
                ('min_order', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للطلب')),
                ('max_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'وجبة القاعة',
                'verbose_name_plural': 'وجبات القاعات',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المكون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المكون')),
                ('is_allergen', models.BooleanField(default=False, verbose_name='مسبب للحساسية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/main/', verbose_name='الصورة الرئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مكون',
                'verbose_name_plural': 'المكونات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ingredients/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صورة المكون',
                'verbose_name_plural': 'صور المكونات',
                'ordering': ['order', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوجبة')),
                ('description', models.TextField(verbose_name='وصف الوجبة')),
                ('meal_type', models.CharField(choices=[('breakfast', 'إفطار'), ('lunch', 'غداء'), ('dinner', 'عشاء'), ('snack', 'سناك'), ('buffet', 'بوفيه'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع الوجبة')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر للفرد')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح للطلب')),
                ('preparation_time', models.PositiveIntegerField(help_text='مدة التحضير بالدقائق', verbose_name='مدة التحضير')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/main/', verbose_name='الصورة الرئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'وجبة',
                'verbose_name_plural': 'الوجبات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meals/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صورة الوجبة',
                'verbose_name_plural': 'صور الوجبات',
                'ordering': ['order', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, verbose_name='الكمية')),
                ('is_optional', models.BooleanField(default=False, verbose_name='اختياري')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مكون الوجبة',
                'verbose_name_plural': 'مكونات الوجبات',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_approved', 'تم الموافقة على الحجز'), ('booking_rejected', 'تم رفض الحجز'), ('booking_cancelled', 'تم إلغاء الحجز'), ('booking_completed', 'تم إكمال الحجز'), ('booking_reminder', 'تذكير بالحجز'), ('general', 'إشعار عام')], max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='رقم الحجز')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('event_title', models.CharField(max_length=200, verbose_name='عنوان الحدث')),
                ('event_description', models.TextField(verbose_name='وصف الحدث')),
                ('start_datetime', models.DateTimeField(verbose_name='تاريخ ووقت البداية')),
                ('end_datetime', models.DateTimeField(verbose_name='تاريخ ووقت النهاية')),
                ('attendees_count', models.PositiveIntegerField(verbose_name='عدد الحضور')),
                ('hall_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر القاعة')),
                ('meals_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي سعر الوجبات')),
                ('services_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي سعر الخدمات')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BookingMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات خاصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_meals', to='hall_booking.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'وجبة الحجز',
                'verbose_name_plural': 'وجبات الحجز',
            },
        ),
        migrations.CreateModel(
            name='BookingMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر للفرد')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الإجمالي')),
                ('serving_time', models.TimeField(blank=True, null=True, verbose_name='وقت التقديم')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات خاصة')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='نباتي')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='نباتي صرف')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='خال من الجلوتين')),
                ('is_halal', models.BooleanField(default=True, verbose_name='حلال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='hall_booking.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'وجبة مطلوبة في الحجز',
                'verbose_name_plural': 'الوجبات المطلوبة في الحجوزات',
                'ordering': ['serving_time', 'meal__name'],
            },
        ),
    ]
