# Generated by Django 5.2.4 on 2025-09-07 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-building', max_length=50, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'فئة القاعة',
                'verbose_name_plural': 'فئات القاعات',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المحافظة')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود المحافظة')),
                ('region', models.CharField(choices=[('cairo', 'القاهرة الكبرى'), ('delta', 'الدلتا'), ('canal', 'قناة السويس'), ('sinai', 'سيناء'), ('red_sea', 'البحر الأحمر'), ('upper_egypt', 'صعيد مصر'), ('new_valley', 'الوادي الجديد')], max_length=50, verbose_name='المنطقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المدينة/المركز')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('is_capital', models.BooleanField(default=False, verbose_name='عاصمة المحافظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='hall_booking.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مدينة/مركز',
                'verbose_name_plural': 'المدن والمراكز',
                'ordering': ['governorate', 'name'],
                'unique_together': {('name', 'governorate')},
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القاعة')),
                ('address', models.TextField(help_text='الشارع، الحي، معالم مميزة', verbose_name='العنوان التفصيلي')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('capacity', models.PositiveIntegerField(verbose_name='السعة')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر للساعة')),
                ('image', models.ImageField(upload_to='halls/', verbose_name='الصورة')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('maintenance', 'صيانة'), ('booked', 'محجوز')], default='available', max_length=20, verbose_name='الحالة')),
                ('features', models.JSONField(default=list, verbose_name='المميزات')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.category', verbose_name='الفئة')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.city', verbose_name='المدينة/المركز')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'قاعة',
                'verbose_name_plural': 'القاعات',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='رقم الحجز')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('event_title', models.CharField(max_length=200, verbose_name='عنوان الحدث')),
                ('event_description', models.TextField(verbose_name='وصف الحدث')),
                ('start_datetime', models.DateTimeField(verbose_name='تاريخ ووقت البداية')),
                ('end_datetime', models.DateTimeField(verbose_name='تاريخ ووقت النهاية')),
                ('attendees_count', models.PositiveIntegerField(verbose_name='عدد الحضور')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.hall', verbose_name='القاعة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='halls/gallery/', verbose_name='الصورة')),
                ('image_type', models.CharField(choices=[('main', 'صورة رئيسية'), ('gallery', 'معرض الصور'), ('interior', 'صور داخلية'), ('exterior', 'صور خارجية'), ('facilities', 'صور المرافق')], default='gallery', max_length=20, verbose_name='نوع الصورة')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الصورة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الصورة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='صورة مميزة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hall_booking.hall', verbose_name='القاعة')),
            ],
            options={
                'verbose_name': 'صورة قاعة',
                'verbose_name_plural': 'صور القاعات',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HallManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'عرض فقط'), ('manage', 'إدارة كاملة'), ('schedule', 'إدارة الجدولة فقط')], default='manage', max_length=20, verbose_name='مستوى الصلاحية')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='hall_booking.hall', verbose_name='القاعة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مدير قاعة',
                'verbose_name_plural': 'مديري القاعات',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_approved', 'تم الموافقة على الحجز'), ('booking_rejected', 'تم رفض الحجز'), ('booking_cancelled', 'تم إلغاء الحجز'), ('booking_completed', 'تم إكمال الحجز'), ('booking_reminder', 'تذكير بالحجز'), ('general', 'إشعار عام')], max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hall_booking.booking', verbose_name='الحجز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
