# Generated by Django 5.2.6 on 2025-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_admin_block',
            field=models.BooleanField(default=False, verbose_name='حجب إداري'),
        ),
    ]
