# Generated by Django 5.2.6 on 2025-09-16 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall_booking', '0001_initial'),
        ('meal_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmealitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_system.hallmeal', verbose_name='الوجبة'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='hall_booking.booking', verbose_name='الحجز'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.additionalservice', verbose_name='الخدمة'),
        ),
        migrations.AddField(
            model_name='bookingserviceitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن الخدمة'),
        ),
        migrations.AddField(
            model_name='bookingserviceitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='hall_booking.booking', verbose_name='الحجز'),
        ),
        migrations.AddField(
            model_name='bookingserviceitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_system.halladditionalservice', verbose_name='الخدمة'),
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='hall_booking.governorate', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='hall',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.category', verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='hall',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.city', verbose_name='المدينة/المركز'),
        ),
        migrations.AddField(
            model_name='hall',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.governorate', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.hall', verbose_name='القاعة'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='hall_booking.hall', verbose_name='القاعة'),
        ),
        migrations.AddField(
            model_name='hallimage',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hall_booking.hall', verbose_name='القاعة'),
        ),
        migrations.AddField(
            model_name='hallmanager',
            name='hall',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='hall_booking.hall', verbose_name='القاعة'),
        ),
        migrations.AddField(
            model_name='hallmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='hallmeal',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_meals', to='hall_booking.hall', verbose_name='القاعة'),
        ),
        migrations.AddField(
            model_name='bookingmeal',
            name='hall_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.hallmeal', verbose_name='وجبة القاعة'),
        ),
        migrations.AddField(
            model_name='ingredientimage',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hall_booking.ingredient', verbose_name='المكون'),
        ),
        migrations.AddField(
            model_name='hallmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.meal', verbose_name='الوجبة'),
        ),
        migrations.AddField(
            model_name='mealimage',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_images', to='hall_booking.meal', verbose_name='الوجبة'),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.ingredient', verbose_name='المكون'),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.meal', verbose_name='الوجبة'),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(through='hall_booking.MealIngredient', to='hall_booking.ingredient', verbose_name='المكونات'),
        ),
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hall_booking.booking', verbose_name='الحجز'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'governorate')},
        ),
        migrations.AlterUniqueTogether(
            name='hallmeal',
            unique_together={('hall', 'meal')},
        ),
        migrations.AlterUniqueTogether(
            name='mealingredient',
            unique_together={('meal', 'ingredient')},
        ),
    ]
