# Generated by Django 5.2.6 on 2025-09-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0002_add_related_names_and_admin_block'),
        ('hall_booking', '0003_add_related_names_and_admin_block'),
    ]

    operations = [
    ]
