# Generated by Django 5.2.4 on 2025-09-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0003_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallimage',
            options={'ordering': ['order', '-uploaded_at'], 'verbose_name': 'صورة قاعة', 'verbose_name_plural': 'صور القاعات'},
        ),
        migrations.AddField(
            model_name='hallimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='hallimage',
            name='image_type',
            field=models.CharField(choices=[('main', 'صورة رئيسية'), ('gallery', 'معرض الصور'), ('interior', 'صور داخلية'), ('exterior', 'صور خارجية'), ('facilities', 'صور المرافق')], default='gallery', max_length=20, verbose_name='نوع الصورة'),
        ),
        migrations.AddField(
            model_name='hallimage',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='صورة مميزة'),
        ),
        migrations.AddField(
            model_name='hallimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='hallimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الصورة'),
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(upload_to='halls/gallery/', verbose_name='الصورة'),
        ),
        migrations.CreateModel(
            name='HallManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'عرض فقط'), ('manage', 'إدارة كاملة'), ('schedule', 'إدارة الجدولة فقط')], default='manage', max_length=20, verbose_name='مستوى الصلاحية')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='hall_booking.hall', verbose_name='القاعة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مدير قاعة',
                'verbose_name_plural': 'مديري القاعات',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
