# Generated by Django 5.2.6 on 2025-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0004_merge_20250920_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='a7jazili', max_length=200, verbose_name='اسم الموقع')),
                ('site_name_ar', models.CharField(default='احجزلي', max_length=200, verbose_name='اسم الموقع بالعربية')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo/', verbose_name='شعار الموقع')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_icons/', verbose_name='أيقونة الموقع')),
                ('phone_primary', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف الأساسي')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف الثانوي')),
                ('email_primary', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني الأساسي')),
                ('email_secondary', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني الثانوي')),
                ('address', models.TextField(blank=True, verbose_name='العنوان الكامل')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='البلد')),
                ('facebook_url', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('twitter_url', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('instagram_url', models.URLField(blank=True, verbose_name='رابط انستجرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='رابط لينكد إن')),
                ('youtube_url', models.URLField(blank=True, verbose_name='رابط يوتيوب')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='رقم واتساب')),
                ('telegram_url', models.URLField(blank=True, verbose_name='رابط تليجرام')),
                ('footer_text', models.TextField(blank=True, default='جميع الحقوق محفوظة', verbose_name='نص الفوتر')),
                ('copyright_year', models.IntegerField(default=2024, verbose_name='سنة حقوق النشر')),
                ('meta_description', models.TextField(blank=True, verbose_name='وصف الموقع (SEO)')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='كلمات مفتاحية (SEO)')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='ساعات العمل')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الدعم الفني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
