# Generated by Django 5.2.4 on 2025-09-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallMealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_meal_categories/', verbose_name='صورة التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('min_selections', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى للاختيار')),
                ('max_selections', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للاختيار')),
                ('is_required', models.BooleanField(default=False, verbose_name='إجباري')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_categories', to='hall_booking.hall', verbose_name='القاعة')),
            ],
            options={
                'verbose_name': 'تصنيف وجبات القاعة',
                'verbose_name_plural': 'تصنيفات وجبات القاعات',
                'ordering': ['hall', 'order', 'name'],
                'unique_together': {('hall', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HallMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوجبة')),
                ('description', models.TextField(verbose_name='وصف الوجبة')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الأساسي')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_meals/', verbose_name='صورة الوجبة')),
                ('order_in_category', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض في التصنيف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='hall_booking.hall', verbose_name='القاعة')),
                ('category', models.ForeignKey(help_text='يجب اختيار تصنيف موجود مسبقاً', on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='meal_system.hallmealcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'وجبة قاعة',
                'verbose_name_plural': 'وجبات القاعات',
                'ordering': ['category', 'order_in_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HallMealComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المكون')),
                ('component_type', models.CharField(choices=[('main', 'طبق رئيسي'), ('side', 'طبق جانبي'), ('salad', 'سلطة'), ('sauce', 'صوص'), ('bread', 'خبز'), ('drink', 'مشروب'), ('dessert', 'حلويات'), ('other', 'أخرى')], default='main', max_length=20, verbose_name='نوع المكون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_components/', verbose_name='صورة المكون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_components', to='hall_booking.hall', verbose_name='القاعة')),
            ],
            options={
                'verbose_name': 'مكون وجبة القاعة',
                'verbose_name_plural': 'مكونات وجبات القاعات',
                'ordering': ['name'],
                'unique_together': {('hall', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HallMealComponentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('is_optional', models.BooleanField(default=False, verbose_name='اختياري')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر إضافي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_system.hallmealcomponent', verbose_name='المكون')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_components', to='meal_system.hallmeal', verbose_name='الوجبة')),
            ],
            options={
                'verbose_name': 'مكون الوجبة',
                'verbose_name_plural': 'مكونات الوجبات',
                'ordering': ['order', 'component__name'],
                'unique_together': {('meal', 'component')},
            },
        ),
        migrations.AddField(
            model_name='hallmeal',
            name='components',
            field=models.ManyToManyField(related_name='meals', through='meal_system.HallMealComponentItem', through_fields=('meal', 'component'), to='meal_system.hallmealcomponent', verbose_name='المكونات'),
        ),
        migrations.AlterUniqueTogether(
            name='hallmeal',
            unique_together={('hall', 'category', 'name')},
        ),
    ]
