# Generated by Django 5.2.6 on 2025-09-14 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal_categories/', verbose_name='صورة الصنف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صنف الوجبات',
                'verbose_name_plural': 'أصناف الوجبات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المكون')),
                ('component_type', models.CharField(choices=[('main', 'طبق رئيسي'), ('side', 'طبق جانبي'), ('salad', 'سلطة'), ('sauce', 'صوص'), ('bread', 'خبز'), ('drink', 'مشروب'), ('dessert', 'حلويات'), ('other', 'أخرى')], default='main', max_length=20, verbose_name='نوع المكون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='الكمية')),
                ('is_optional', models.BooleanField(default=False, verbose_name='اختياري')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مكون وجبة',
                'verbose_name_plural': 'مكونات الوجبات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealComponentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meal_components/', verbose_name='صورة المكون')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='meal_system.mealcomponent')),
            ],
            options={
                'verbose_name': 'صورة مكون وجبة',
                'verbose_name_plural': 'صور مكونات الوجبات',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوجبة')),
                ('description', models.TextField(verbose_name='وصف الوجبة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meal_system.mealcategory', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'وجبة',
                'verbose_name_plural': 'الوجبات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='meal_system.mealitem', verbose_name='الوجبة'),
        ),
        migrations.CreateModel(
            name='MealItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meals/', verbose_name='صورة الوجبة')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='meal_system.mealitem')),
            ],
            options={
                'verbose_name': 'صورة وجبة',
                'verbose_name_plural': 'صور الوجبات',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
