# Generated by Django 5.2.6 on 2025-09-14 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal_categories/', verbose_name='صورة الصنف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صنف الوجبات',
                'verbose_name_plural': 'أصناف الوجبات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المكون')),
                ('component_type', models.CharField(choices=[('main', 'طبق رئيسي'), ('side', 'طبق جانبي'), ('salad', 'سلطة'), ('sauce', 'صوص'), ('bread', 'خبز'), ('drink', 'مشروب'), ('dessert', 'حلويات'), ('other', 'أخرى')], default='main', max_length=20, verbose_name='نوع المكون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مكون الوجبة',
                'verbose_name_plural': 'مكونات الوجبات',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HallMealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_meal_categories/', verbose_name='صورة التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('min_selections', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى للاختيار')),
                ('max_selections', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للاختيار')),
                ('is_required', models.BooleanField(default=False, verbose_name='إجباري')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_categories', to='hall_booking.hall', verbose_name='القاعة')),
            ],
            options={
                'verbose_name': 'تصنيف وجبات القاعة',
                'verbose_name_plural': 'تصنيفات وجبات القاعات',
                'ordering': ['hall', 'order', 'name'],
                'unique_together': {('hall', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HallMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_category', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض في التصنيف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوجبة')),
                ('description', models.TextField(verbose_name='وصف الوجبة')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الأساسي')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_meals/', verbose_name='صورة الوجبة')),
                ('min_components', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى للمكونات المطلوبة')),
                ('max_components', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للمكونات المسموح بها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='hall_booking.hall', verbose_name='القاعة')),
                ('category', models.ForeignKey(help_text='يجب اختيار تصنيف موجود مسبقاً', on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='meal_system.hallmealcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'وجبة القاعة',
                'verbose_name_plural': 'وجبات القاعات',
                'ordering': ['name'],
                'unique_together': {('hall', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HallMealComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المكون')),
                ('component_type', models.CharField(choices=[('main', 'طبق رئيسي'), ('side', 'طبق جانبي'), ('salad', 'سلطة'), ('sauce', 'صوص'), ('bread', 'خبز'), ('drink', 'مشروب'), ('dessert', 'حلويات'), ('other', 'أخرى')], default='main', max_length=20, verbose_name='نوع المكون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_components/', verbose_name='صورة المكون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_components', to='hall_booking.hall', verbose_name='القاعة')),
            ],
            options={
                'verbose_name': 'مكون وجبات القاعة',
                'verbose_name_plural': 'مكونات وجبات القاعات',
                'ordering': ['hall', 'component_type', 'name'],
                'unique_together': {('hall', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HallMealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات خاصة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to='hall_booking.booking', verbose_name='الحجز')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meal_system.hallmeal', verbose_name='الوجبة')),
            ],
            options={
                'verbose_name': 'طلب وجبة',
                'verbose_name_plural': 'طلبات الوجبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealComponentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meal_components/', verbose_name='صورة المكون')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='meal_system.mealcomponent')),
            ],
            options={
                'verbose_name': 'صورة مكون وجبة',
                'verbose_name_plural': 'صور مكونات الوجبات',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوجبة')),
                ('description', models.TextField(verbose_name='وصف الوجبة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meal_system.mealcategory', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'وجبة',
                'verbose_name_plural': 'الوجبات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meals/', verbose_name='صورة الوجبة')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='meal_system.mealitem')),
            ],
            options={
                'verbose_name': 'صورة وجبة',
                'verbose_name_plural': 'صور الوجبات',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HallMealCategoryMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_meals', to='meal_system.hallmealcategory', verbose_name='التصنيف')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_categories', to='meal_system.hallmeal', verbose_name='الوجبة')),
            ],
            options={
                'verbose_name': 'تصنيف الوجبة',
                'verbose_name_plural': 'تصنيفات الوجبات',
                'ordering': ['category', 'order', 'meal__name'],
                'unique_together': {('category', 'meal')},
            },
        ),
        migrations.CreateModel(
            name='HallMealOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meal_system.hallmealcomponent', verbose_name='المكون')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='meal_system.hallmealorder', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مكون الطلب',
                'verbose_name_plural': 'مكونات الطلبات',
                'unique_together': {('order', 'component')},
            },
        ),
        migrations.CreateModel(
            name='MealComponentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='إجباري')),
                ('max_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الحد الأقصى للكمية')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر إضافي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_system.hallmealcomponent', verbose_name='المكون')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_component_items', to='meal_system.hallmeal', verbose_name='الوجبة')),
            ],
            options={
                'verbose_name': 'مكون الوجبة',
                'verbose_name_plural': 'مكونات الوجبات',
                'ordering': ['order', 'component__name'],
                'unique_together': {('meal', 'component')},
            },
        ),
        migrations.CreateModel(
            name='MealItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='الكمية')),
                ('is_optional', models.BooleanField(default=False, verbose_name='اختياري')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_system.mealcomponent', verbose_name='المكون')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_components', to='meal_system.mealitem', verbose_name='الوجبة')),
            ],
            options={
                'verbose_name': 'مكون الوجبة',
                'verbose_name_plural': 'مكونات الوجبات',
                'ordering': ['order'],
                'unique_together': {('meal', 'component')},
            },
        ),
    ]
