# Generated by Django 5.2.6 on 2025-09-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealcomponent',
            options={'ordering': ['component_type', 'name'], 'verbose_name': 'مكون الوجبة', 'verbose_name_plural': 'مكونات الوجبات'},
        ),
        migrations.RemoveField(
            model_name='mealcomponent',
            name='is_optional',
        ),
        migrations.RemoveField(
            model_name='mealcomponent',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealcomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='mealcomponent',
            name='quantity',
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.CreateModel(
            name='MealItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='الكمية')),
                ('is_optional', models.BooleanField(default=False, verbose_name='اختياري')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_system.mealcomponent', verbose_name='المكون')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_components', to='meal_system.mealitem', verbose_name='الوجبة')),
            ],
            options={
                'verbose_name': 'مكون الوجبة',
                'verbose_name_plural': 'مكونات الوجبات',
                'ordering': ['order'],
                'unique_together': {('meal', 'component')},
            },
        ),
    ]
