# Generated by Django 5.2.4 on 2025-09-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0001_initial'),
        ('meal_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الخدمة')),
                ('price', models.DecimalField(decimal_places=2, help_text='سعر الخدمة الإضافية بالريال', max_digits=10, verbose_name='سعر الخدمة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_additional_services', to='hall_booking.hall', verbose_name='القاعة')),
            ],
            options={
                'verbose_name': 'خدمة إضافية',
                'verbose_name_plural': 'الخدمات الإضافية',
                'ordering': ['name'],
                'unique_together': {('hall', 'name')},
            },
        ),
    ]
